#!/bin/bash

# git reset --hard in-case make clean was run and deleted toolchain files..
git reset --hard;

# Try to parallelize the build for faster performance.
JOBS="$(cat /proc/cpuinfo | grep -c processor)";

# Determine Make flags
MAKE_FLAGS=-j"$JOBS"

# Kernel configuration
make ARCH=x86 ubuntu_defconfig

# start the build
time make ARCH=x86 $MAKE_FLAGS bzImage && time make ARCH=x86 modules;

echo "Time to install the kernel binary and modules which must run as root.";
echo "Enter Admin password to continue";
sleep 15;
sudo make $MAKE_FLAGS install && sudo make $MAKE_FLAGS modules_install;
echo "reboot to new kernel";
sudo reboot;
